apiVersion: v1
kind: Service
metadata:
  name: monolithic-service
  namespace: monolithic-arch
spec:
  selector:
    app: monolithic-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
